### ISSUE TITLE
My common words It has only connective words

### ISSUE THREAD

**Issue by johnfelipe** [SpringtideCollectiveOrg/openhousens.ca#48]
http://concejodemedellin.felipeurrego.com/

How fix it?

**Comment by jpmckinney** [comment]
Please use the https://github.com/mysociety/sayit or https://github.com/mysociety/sayit.mysociety.org/ issue queues. This is not a repository for general support.

**Comment by johnfelipe** [comment]
But common words its only yours?

**Comment by jpmckinney** [comment]
You need to edit the list of words here to exclude connecting words: https://github.com/SpringtideCollectiveOrg/openhousens.ca/blob/fa23e7aa058d14a8a949713797eb20497c6dd7c1/legislature/views.py#L23

**Comment by johnfelipe** [comment]
https://gist.github.com/johnfelipe/9b74b8a4f9667ac9ecde

And still show connecting words:

![7](https://cloud.githubusercontent.com/assets/428820/7644767/9cf74ef4-fa6f-11e4-9933-a6ea72778a78.png)
![6](https://cloud.githubusercontent.com/assets/428820/7644768/9cf9b14e-fa6f-11e4-8e16-7a8cc543ea74.png)
![5](https://cloud.githubusercontent.com/assets/428820/7644769/9cfcbe7a-fa6f-11e4-95d5-be3a833b968c.png)
![4](https://cloud.githubusercontent.com/assets/428820/7644770/9d01e814-fa6f-11e4-9256-9347402e52cb.png)
![3](https://cloud.githubusercontent.com/assets/428820/7644772/9d40307e-fa6f-11e4-8c35-102b9823f0ac.png)
![2](https://cloud.githubusercontent.com/assets/428820/7644773/9d4c1114-fa6f-11e4-8053-769f9de961a7.png)
![1](https://cloud.githubusercontent.com/assets/428820/7644771/9d0cbd2a-fa6f-11e4-901c-59683ff66788.png)

**Comment by jpmckinney** [comment]
Seems to be just those with accents. Try:

```
from unicodedata import normalize
```

And replace `strip_tags(speech.text).lower()` with:

```
normalize('NFC', strip_tags(speech.text).lower())
```

**Comment by johnfelipe** [comment]
https://github.com/johnfelipe/top9ypalabrascomunes/blob/master/speeches/templatetags/speech_extension.py#L10

https://github.com/johnfelipe/top9ypalabrascomunes/blob/master/speeches/templatetags/speech_extension.py#L59

sudo /etc/init.d/gunicorn restart

Still same problem

**Comment by jpmckinney** [comment]
I'm out of ideas. Good luck!

**Comment by johnfelipe** [comment]
Hi again, how delete word with **ñ** and á, é, í, ó, pls help
