### ISSUE TITLE
How put The latest transcript is from...

### ISSUE THREAD

**Issue by johnfelipe** [SpringtideCollectiveOrg/openhousens.ca#49]
Please guide me how implement **The latest transcript is from**

**Comment by jpmckinney** [comment]
see:

https://github.com/SpringtideCollectiveOrg/openhousens.ca/blob/master/legislature/templates/home.html#L24

https://github.com/SpringtideCollectiveOrg/openhousens.ca/blob/master/legislature/views.py#L59
