### ISSUE TITLE
common words responsive design

### ISSUE THREAD

**Issue by johnfelipe** [SpringtideCollectiveOrg/openhousens.ca#50]
Is possible do responsive design common words?
![screenshot_2015-05-22-00-42-48](https://cloud.githubusercontent.com/assets/428820/7764786/df3e2010-001b-11e5-943e-efb8378a6d52.png)

**Comment by jpmckinney** [comment]
If you resize an existing window, the words will not resize. But if you load the page on a small window, the words will be an appropriate size. So, it looks fine on tablets, phones, etc.
