### ISSUE TITLE
common words is slow

### ISSUE THREAD

**Issue by johnfelipe** [SpringtideCollectiveOrg/openhousens.ca#51]
https://github.com/mysociety/sayit/issues/488, answer is: https://github.com/mysociety/sayit/issues/488#issuecomment-104872264, how fix that slow issue?

**Comment by jpmckinney** [comment]
It's exactly as Matthew Somerville wrote in that issue. Don't do `Speech.objects.all()`. Take a subset of all speeches. This repository takes only one hansard: https://github.com/SpringtideCollectiveOrg/openhousens.ca/blob/master/legislature/views.py#L59
