### ISSUE TITLE
how to output latest speech ('last_speech') by date at homepage

### ISSUE THREAD

**Issue by illucent** [SpringtideCollectiveOrg/openhousens.ca#52]
hi! can you please code snippet for 'last_speech'.

**Comment by jpmckinney** [comment]
Have a look at the home method in views.py and the home.html template.

**Comment by illucent** [comment]
yes i copied form openhousens.ca repo and tested; no results both ways ( /templatetags and views.py ). it is applicable to django.sayit which are almost identical to openhousens
the only difference is app name ( not legislature )
http://demo2016.asambleadelosaraucanos.co/

**Comment by jpmckinney** [comment]
I suggest raising the issue on the SayIt repository: https://github.com/mysociety/sayit

This repository is just meant specifically for the development of the openhousens.ca website, not for support issues.

**Comment by illucent** [comment]
thanks!
